sudo: required
services:
  - docker

before_install:
  - docker build -t ravi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ravi/docker-react npm run test

deploy:
  provider : elasticbeanstalk
  region : "ap-south-1"
  app : "frontend"
  env : "Frontend-env"
  bucket_name : "elasticbeanstalk-ap-south-1-905418435396"
  bucket_path : "frontend"
  on:
    branch : master
  access_key_id : $AWS_ACCESS_KEY_ID
  secret_access_key : $AWS_SECRET_ACCESS_KEY